# Generated by Django 2.0.7 on 2019-05-24 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0003_auto_20190524_1512'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ques',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asked', models.CharField(max_length=150)),
                ('time_asked', models.TimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.ForeignKey(on_delete=True, to='user.User')),
            ],
        ),
    ]
