# Generated by Django 2.0.7 on 2019-06-02 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Question', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ans',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ans', models.CharField(max_length=1000)),
                ('by', models.CharField(max_length=20)),
                ('ques_id', models.ForeignKey(on_delete='CASCADE', to='Question.Ques')),
            ],
        ),
    ]
