# Generated by Django 2.0.7 on 2019-06-02 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Question', '0002_ans'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ques',
            old_name='id',
            new_name='id1',
        ),
    ]
