# Generated by Django 2.0.7 on 2019-06-02 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Question', '0004_auto_20190602_1502'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ques',
            old_name='id1',
            new_name='id',
        ),
    ]
