# Generated by Django 2.0.7 on 2019-06-02 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Question', '0006_auto_20190602_1506'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ans',
            name='ques_id',
        ),
        migrations.DeleteModel(
            name='Ans',
        ),
        migrations.DeleteModel(
            name='Ques',
        ),
    ]
