# Generated by Django 2.0.7 on 2019-06-02 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Question', '0007_auto_20190602_1516'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ques',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name="person's name")),
                ('ques', models.CharField(default=None, max_length=150, unique=True)),
                ('time', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
