# Generated by Django 2.0.7 on 2019-06-02 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Question', '0009_ans'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ans',
            name='ques_id',
        ),
        migrations.RemoveField(
            model_name='ques',
            name='time',
        ),
        migrations.AlterField(
            model_name='ques',
            name='ques',
            field=models.CharField(max_length=150),
        ),
        migrations.DeleteModel(
            name='Ans',
        ),
    ]
