# Generated by Django 2.0.7 on 2019-06-03 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Question', '0012_historicalans_historicalques'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalans',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='historicalans',
            name='ques_id',
        ),
        migrations.RemoveField(
            model_name='historicalques',
            name='history_user',
        ),
        migrations.DeleteModel(
            name='HistoricalAns',
        ),
        migrations.DeleteModel(
            name='HistoricalQues',
        ),
    ]
