# Generated by Django 2.0.7 on 2019-05-24 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('name', models.CharField(db_index=True, max_length=50)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('password', models.CharField(max_length=20, unique=True)),
                ('mobilenumber', models.IntegerField()),
                ('createdtime', models.TimeField(auto_now_add=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
