# Generated by Django 2.0.7 on 2019-05-29 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20190527_1850'),
    ]

    operations = [
        migrations.AlterField(
            model_name='login',
            name='Password',
            field=models.CharField(max_length=20),
        ),
    ]
