# Generated by Django 2.0.7 on 2019-06-03 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_historicallogin_historicalprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicallogin',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='historicalprofile',
            name='history_user',
        ),
        migrations.DeleteModel(
            name='Historicallogin',
        ),
        migrations.DeleteModel(
            name='Historicalprofile',
        ),
    ]
